chore: set envs according to new workflow api

diff --git a/.github/workflows/python-test-badge.yml b/.github/workflows/python-test-badge.yml
--- a/.github/workflows/python-test-badge.yml
+++ b/.github/workflows/python-test-badge.yml
@@ -22,10 +22,10 @@ jobs:
       - name: Test the code
         run: |
           tox &> out.txt
-          echo "::set-env name=PASSING::$([ $? == 0 ] && echo -n passing || echo -n failed)"
-          echo "::set-env name=PASSING_ERR::$([ env.PASSING == "passing" ] && echo -n true || echo -n false)"
-          echo "::set-env name=COVERAGE::$(grep TOTAL out.txt | awk '{print $4}' | tr -d '%\n')"
-          echo "::set-env name=RELEASE_VERSION::$(grep version healthcheck_python/release.py | awk '{print $3}' | tr -d \''\n')"
+          echo "PASSING=$([ $? == 0 ] && echo -n passing || echo -n failed)" >> $GITHUB_ENV
+          echo "PASSING_ERR=$([ env.PASSING == "passing" ] && echo -n true || echo -n false)" >> $GITHUB_ENV
+          echo "COVERAGE=$(grep TOTAL out.txt | awk '{print $4}' | tr -d '%\n')" >> $GITHUB_ENV
+          echo "RELEASE_VERSION=$(grep version healthcheck_python/release.py | awk '{print $3}' | tr -d \''\n')" >> $GITHUB_ENV
       - name: Create coverage badge
         uses: schneegans/dynamic-badges-action@v1.0.0
         with:
